Create a minor account
AjuntamentdeBarcelona/decidim-module-kids pull request #27
Opened 2022-11-07 11:07 UTC by antopalidi

In this PR, added the ability to create and edit a minor's account

- [ ] add a configuration variable a maximum number of minors 
- [ ] add button "new minor account"
- [ ] add form for creating a minor
- [ ] add command for creating a minor
- [ ] send a confirmation email to the recently minor user created
- [ ] edit a minor
- [ ] add a button link to verify the minor account

2022-11-11 13:50 UTC, microstudi reviewed
some quick notes!

2022-11-11 13:50 UTC, microstudi commented on spec/commands/create_minor_account_spec.rb
> +    describe "call" do
this describe is unnecessary

2022-11-11 13:50 UTC, microstudi commented on spec/commands/create_minor_account_spec.rb
> +      let!(:tutor) { create(:user, :confirmed, organization:) }
```suggestion
      let!(:current_user) { create(:user, :confirmed, organization:) }
```

2022-11-11 13:50 UTC, microstudi commented on spec/commands/create_minor_account_spec.rb
> +      end
```suggestion
```
All of this should be unnecessary

2022-11-11 13:50 UTC, microstudi commented on spec/commands/create_minor_account_spec.rb
> +      end
```suggestion
```
Unnecessary

2022-11-11 13:50 UTC, microstudi commented on spec/commands/create_minor_account_spec.rb
> +      let!(:command) { described_class.new(form, tutor) }
```suggestion
      let!(:command) { described_class.new(form, current_user) }
```

2022-11-15 10:03 UTC, microstudi requested changes
Thanks Anna,
we still need to improve this a little.

1. We need to add more tests, for the form, controller and system tests (see comments).
2. There will be no "show" action , let's remove all the methods and views refering to it please
3. On the other hand, we need to update the flow a little.
  - When a user is created, the tutor needs to  be redirected to the verification step BEFORE sending any emails.
  - When the user is verified properly, then we send the welcome email.

2022-11-15 10:03 UTC, microstudi commented on app/controllers/decidim/kids/user_minors_controller.rb
> +        @minor_user = minors.find_by(id: params[:id])
```suggestion
        @minor_user ||= minors.find_by(id: params[:id])
```
memoize

2022-11-15 10:03 UTC, microstudi commented on app/controllers/decidim/kids/user_minors_controller.rb
> +        @form = form(Decidim::Kids::MinorAccountForm).from_model(minor_user.minor_data)
```suggestion
        @form ||= form(Decidim::Kids::MinorAccountForm).from_model(minor_user.minor_data)
```
let's memoize this

2022-11-15 10:03 UTC, microstudi commented on app/controllers/decidim/kids/user_minors_controller.rb
> +        return unless tutor_verified?
```suggestion
```

This should be unnecessary (see NeedsTutorAuthorization), although we should check that is tested

2022-11-15 10:03 UTC, microstudi commented on app/controllers/decidim/kids/user_minors_controller.rb
> +        return unless tutor_verified?
```suggestion
```

2022-11-15 10:03 UTC, microstudi commented on spec/permissions/permissions_spec.rb
> +    # context "when edit action" do
We need to test the "edit" action here

2022-11-15 10:03 UTC, microstudi commented on app/views/decidim/kids/user_minors/new.html.erb
> +            <%= form.check_box :tos_agreement, label: minor_tos, id: "minor_tos_agreement", disabled: false %>
minor_tos should point to the page `minors-terms` (this page should be created automatically when enabling minors in /system.

Also, I think we should print the content of the page here (similar as when you answer a questionnaire)

2022-11-15 10:03 UTC, microstudi commented on app/commands/decidim/kids/update_minor_account.rb
> +          password: form.password
```suggestion
```

We should not keept the password here, we can store it as the normal password in the user database

2022-11-15 10:03 UTC, microstudi commented on app/forms/decidim/kids/minor_account_form.rb
> +
Needs to validate the terms and conditions (add a test too)

2022-11-15 10:03 UTC, microstudi commented on app/forms/decidim/kids/minor_account_form.rb
> +      validates :birthday, presence: true # format: { with: /\A\d{8}\z/ }
Needs to validate that the age is within accepted range

2022-11-15 10:03 UTC, microstudi commented on app/forms/decidim/kids/minor_account_form.rb
> +    class MinorAccountForm < Decidim::Form
This whole class needs to be tested

2022-11-15 10:03 UTC, microstudi commented on app/commands/decidim/kids/create_minor_account.rb
> +          send_email_minor
We shouldn't send the email here, after creating a minor, we need to redirect to the authorization step

2022-11-15 10:03 UTC, microstudi commented on app/models/decidim/kids/minor_data.rb
> +      encrypt_attribute :password, type: :string
```suggestion
```

Let's not store the password here.
Also: to do this it would require a migration

2022-11-15 10:03 UTC, microstudi commented on app/views/decidim/kids/user_minors/new.html.erb
> +          </div>
You can probably reuse a common view (called `_form.html.erb`) for the new.html.erb and the edit.html.erb with this fields

2022-11-17 11:33 UTC, fblupi requested changes

2022-11-17 11:33 UTC, fblupi commented on app/forms/decidim/kids/minor_account_form.rb
> +          errors.add(:birthday, I18n.t("decidim.kids.minor_account.form.invalid_age")) unless minor_age.between?(min_minor_age, minimum_adult_age - 1)
I think the `- 1` is not necessary.

```suggestion
          errors.add(:birthday, I18n.t("decidim.kids.minor_account.form.invalid_age")) unless minor_age.between?(min_minor_age, minimum_adult_age)
```

2022-11-17 11:33 UTC, fblupi commented on app/helpers/decidim/kids/user_minors_helper.rb
> +        true
Why don't just leave it like this?

```suggestion
        current_user.minors.count < Decidim::Kids.maximum_minor_accounts
```

2022-11-17 12:00 UTC, microstudi commented on app/forms/decidim/kids/minor_account_form.rb
> +          errors.add(:birthday, I18n.t("decidim.kids.minor_account.form.invalid_age")) unless minor_age.between?(min_minor_age, minimum_adult_age - 1)
Right, but conceptually, maybe we should rename this variable to `maximum_minor_age` or change the other places to add the -1. cos, if the minor's age is already the  `minimum_adult_age`, then it can create an account on his own right?

2022-11-17 12:00 UTC, microstudi commented on app/helpers/decidim/kids/user_minors_helper.rb
> +        true
yep

2022-11-17 12:39 UTC, microstudi commented on app/forms/decidim/kids/minor_account_form.rb
> +          errors.add(:birthday, I18n.t("decidim.kids.minor_account.form.invalid_age")) unless minor_age.between?(min_minor_age, minimum_adult_age - 1)
done

2022-11-17 12:44 UTC, fblupi approved these changes
LGTM 👍 
Great work!

2022-11-17 12:47 UTC, microstudi approved these changes

2022-11-17 12:52 UTC, merged

2022-12-09 13:15 UTC, NilHomedes commented
Hi @microstudi and @antopalidi, great job! Thank yo very much!
I will leave here my review about the minor account creation workflow. But if you prefer, I can create a specific issue.

### 1. Add a minor
- [ ] In general, perhaps a little more information about what is being done would be great. I think we could have an introductory text under the title that says "Fist step: Now you must fill in the form with the necessary information to create the minor's account"
- [ ] Add a help text below e-mail field, specify that the e-mail we are asking for is the minors e-mail. The text should be: "Write here the child's e-mail"
- [ ] Why are we asking here for the password? In the final step (before confirming the email) the minor is asked again to create a password. I think we should remove the password creation of that form. This could works as the invitations do: you create an account with name, nickname and email, but without a password. 

![](https://i.imgur.com/5ZV23kJ.png)


### 2. Verify the minor

![](https://i.imgur.com/mjE2Ymt.png)

- [ ] Add a help text "Second step: For security reasons, we need to check that the minor's details are correct and we can verify his or her identity on our census". This could be below the current help text.

### 3. Pending e-mail confirmation

![](https://i.imgur.com/ykfqNkD.png)
- [ ] It's not clear what is the next step to finish the process. We should add a message that says: "An email have been sent to the minor's email adress. Please confirm the email to finish the process". This could be a modal or an announcement text.


![](https://i.imgur.com/E72yP9d.png)
- [ ] The "Resend e-mail" button shouldn't be like this. Maybe it's better to have an icon to "Resend email"


### 4. Email confirmation
![](https://i.imgur.com/RY9rxZe.png)

- [ ] Instructions text should be:
"Welcome @user! 
Your legal guardian has authorised the creation of your account to participate in the platform. Your account will be under guardianship until you reach the legal age. You can now finalise the account creation by confirming this email and following the instructions"
- [ ] Change "Accept email" for "Confirm email"

2022-12-09 13:40 UTC, microstudi commented
Yes please @NilHomedes make a new for this!