Avoid minors to enter to the authorization section
AjuntamentdeBarcelona/decidim-module-kids pull request #30
Opened 2022-11-16 16:18 UTC by fblupi

Fixes #5 

With this PR, minor users won't be able to access the authorizations page.

- [x] As a minor registered I can be able to log in
- [x] As a minor registered I can be able to change my password
- [x] As a minor registered I can be able to change my profile data, except for my birthday
- [ ] As a minor registered, I can only receive private messages from other underage users.
- [x] As a minor registered I can't be able to access to authorizations page

2022-11-17 13:06 UTC, microstudi requested changes
I see that this is for limiting certain accesses to minor (probably we will add cases in the future).
Not sure that disabling completely the authorization page is the way to go, but we can improve it in the future if needed.

I left you a comment, but, overall, this PR needs tests, probably in the `specs/permissions` folder.

2022-11-17 13:06 UTC, microstudi commented on app/permissions/decidim/kids/permissions.rb
> +          if !user.organization.minors_participation_enabled? || user.minor?
In here if minors participation is disable, no one will be able to access the authorizations. In this case we should do nothing and let the default behaviour.

2022-11-18 10:00 UTC, microstudi requested changes
Thanks @fblupi 
this looks ok but it has a problem if you disable the module in the `/system`, no person is allowed to access authorizations then.

Can we create a `spec/system` test to check the accesses?
we need to make sure when `organization.minors_participation_enabled?` is false that this permissions don't do anything and delegate everything to the normal decidim.

2022-11-18 10:00 UTC, microstudi commented on app/controllers/concerns/decidim/kids/has_minors_permissions.rb
> +    module HasMinorsPermissions
```suggestion
    module HasDecidimKidsPermissions
```
as this is not exclusive for the minors, maybe a more generic name would be better

2022-11-18 10:00 UTC, microstudi commented on app/permissions/decidim/kids/permissions.rb
> +        if !user.organization.minors_participation_enabled? || user.minor? || !user.confirmed?
I think that this line breaks access to authorizations an other parts if you disable the module in `/system`

2022-11-21 11:18 UTC, microstudi reviewed
Hi @fblupi 
Everything looks good, good job!
I would be nice to have and additional integration test (spec/system) to check different accesses to the manipulated controllers. I feel that this kind of minor permission control will expand in the future and it would be nice to have a final test to expand.

i would tests these cases to start:

1. when the module is activated:
  1. If I'm a normal user I can access authorizations and start conversations with anyone exept minors
  2. If I'm a minor I cannot access authorizations and i cannot start conversations with adults (or can I?)
2. when the module is not activated
  1. If I'm a normal user I can access authorizations and start conversations with anyone, even if is a minor (as the module will still be activated it is possible to have former "minor users")
  2. If I'm a minor I can access authorizations and I can start a conversation with an adult (following the same hypothetical case of being a former minor)

2022-11-30 13:06 UTC, fblupi commented
> Hi @fblupi Everything looks good, good job! I would be nice to have and additional integration test (spec/system) to check different accesses to the manipulated controllers. I feel that this kind of minor permission control will expand in the future and it would be nice to have a final test to expand.
> 
> i would tests these cases to start:
> 
> 1. when the module is activated:
> 2. If I'm a normal user I can access authorizations and start conversations with anyone exept minors
> 3. If I'm a minor I cannot access authorizations and i cannot start conversations with adults (or can I?)
> 4. when the module is not activated
> 5. If I'm a normal user I can access authorizations and start conversations with anyone, even if is a minor (as the module will still be activated it is possible to have former "minor users")
> 6. If I'm a minor I can access authorizations and I can start a conversation with an adult (following the same hypothetical case of being a former minor)

Hi @microstudi,
@apuertadelaguila has made the tests you requested

2022-12-15 17:29 UTC, microstudi approved these changes
Sorry for being late! this looks good now!

2022-12-15 17:29 UTC, merged