Tutor impersonates a minor
AjuntamentdeBarcelona/decidim-module-kids pull request #33
Opened 2022-11-28 10:04 UTC by antopalidi

2022-12-15 19:04 UTC, microstudi submitted a review, later dismissed
good!

2022-12-16 10:05 UTC, microstudi commented
@fblupi this should be ready to review

2023-01-10 14:28 UTC, fblupi requested changes

2023-01-10 14:28 UTC, fblupi commented on app/commands/decidim/kids/close_session_managed_minor.rb
> +      # minor_user         - The user to impersonate
There is a difference between the attribute in the comment and the attribute used in the method: `minor_user` vs `real_user`

2023-01-10 14:28 UTC, fblupi commented on app/commands/decidim/kids/impersonate_minor.rb
> +      def initialize(minor_user, current_user, form)
`form` attribute should be documented above

2023-01-23 11:39 UTC, microstudi approved these changes, later dismissed

2023-01-23 16:01 UTC, fblupi approved these changes

2023-01-23 16:02 UTC, merged