[GDPR 16] Enable participatory spaces for minors
AjuntamentdeBarcelona/decidim-module-kids pull request #36
Opened 2022-12-19 13:14 UTC by microstudi

fixes #22

- [x] Add configuration option to specify which participatory spaces are allowed
- [x] Add menu item for every type of participatory space configured
- [x] Do not show the menu or let access the controller if minors is not enabled
- [x] Configure the type of participatory space
- [x] Prevent access to the participatory space according to:
  - [x] **Space for all** If access is global, everyone allowed
  - [x] **Exclusive for minors**
  - [x] **tutors readonly**
  - [x] **Minors without guardianship**:
    - [x] Users authorized with verification method
    - [x] Check age if specified
- [x] Tests

![image](https://user-images.githubusercontent.com/1401520/209188512-e94c5345-64d3-40b6-973d-ad6ba519d910.png)

2023-01-10 15:45 UTC, fblupi requested changes

2023-01-10 15:45 UTC, fblupi commented on app/commands/decidim/kids/admin/save_participatory_space_config.rb
> +      # A command to authorize a user with an authorization handler.
This comment has been copied and pasted and it should be changed because it may cause confusion

2023-01-10 15:45 UTC, fblupi commented on app/controllers/concerns/decidim/kids/participatory_space_context_override.rb
> +            age = ((Time.zone.now - Date.parse(space_authorization.metadata[attr.to_s]).to_time) / 1.year.seconds).floor
This is the fourth place in which we are calculating the age. We could create a method so we don't repeat it so many times.

2023-01-16 11:33 UTC, microstudi commented on app/controllers/concerns/decidim/kids/participatory_space_context_override.rb
> +            age = ((Time.zone.now - Date.parse(space_authorization.metadata[attr.to_s]).to_time) / 1.year.seconds).floor
Right, refactored

2023-01-16 18:02 UTC, microstudi commented
@fblupi changes addressed

2023-01-17 07:50 UTC, fblupi requested changes

2023-01-17 07:50 UTC, fblupi commented on lib/decidim/kids/engine.rb
>            Decidim::Verifications::ApplicationController.include(Decidim::Kids::NeedsAdultPermission)
Tests are failing because this concern has been renamed as `DisableMinorsParticipation`.

2023-01-17 07:52 UTC, fblupi requested changes

2023-01-17 07:52 UTC, fblupi commented on lib/decidim/kids/engine.rb
>            Decidim::Verifications::ApplicationController.include(Decidim::Kids::NeedsAdultPermission)
This line should be deleted as the concern name has been changed and there is no concern named `NeedsAdultPermission` right now

2023-01-17 09:53 UTC, microstudi commented
Looks like this file was removed when rebasing the PR. back in!

2023-01-17 10:28 UTC, microstudi commented
all green @fblupi

2023-01-17 10:31 UTC, fblupi approved these changes
LGTM!

2023-01-17 10:31 UTC, merged